### ISSUE TITLE
Add support for reqwest-middleware 0.3.0

### ISSUE THREAD

**Issue by lededje** [ChorusOne/rvcr#21]
Reqwest updated to 0.12 recently and their implementation of reqwest changed. This required reqwest middleware to update it's implementation which in turn made rvcr incompatible with it's most recent version.

Please can we update reqwest middleware to 0.3

**Comment by lededje** [comment]
The updates I made are as follows:

```toml
reqwest = { version = "0.12.4" }
reqwest-middleware = "0.3.0"
http = "1.0.0"
```

~There is still a lifetime issue on the `handle` method for `impl Middleware` that I'm unable to resolve.~

This looked to be a change in the struct that now references a different argument type.
